### ISSUE TITLE
Make a 'Hello World' utilising Postgres, Flask/FastAPI, & an extremely simple frontend

### ISSUE THREAD

**Issue by anthonycarbone** [CreateUNSW/OWRxCREATE-Database-Venture#16]
We're gonna each do a little training exercise to truly become familiar (at a simple level) with all the stuff we're gonna start playing with. I'd like everyone to make the most simple web app you can, utilising a Postgres database, Flask/FastAPI as the backend framework, and any frontend framework, or even simple HTML+JS. 
On Tuesday of Wk6 @ 2pm we'll have a Teams meeting and showcase our training exercise, and discuss what we found out, and what lessons we can learn.

**Comment by Edwin-Choi** [comment]
I have a suggestion, though you don't have to follow it. 
what I recommend you guys is to downloading the software called [postman](https://www.postman.com/) 
it is one of the tools they would use especially in enterprise or large scale project for testing api endpoint from the backend.
In a nutshell, everything is simplified, in the software, you just need to enter your endpoint address(e.g. 192.168.0.1:3000/myEndPoint) and configure it to send a json in the format you expect and then your endpoint will run according to how you programmed for the endpoint and you can see whatever is returned in postman software.
It's just much easier than actually making HTML + JS or compiling an entire front end project (even though i suppose that gets you to pick up your front end game again and react single page is just one command line lol)
**BUT just putting this software out there so it can make your life easier as you don't NEED a front end to test your back end**
Like, you CAN implement a frontend/ front end framework and make an entire project out of it, or even try both ways, but depending on what you want to do just letting you guys know there is something out there that'll make your backend development life easier and if you want to skip out on frontend effort, it's there to take it out

**Comment by anthonycarbone** [comment]
Great suggestion @Edwin-Choi! Postman is a good way to pretend to have a frontend/website without really making one. Up to you whether you'd like to do so, or make a simple webpage. Would love to hear if you have any more insights re this @Edwin-Choi :)

**Comment by anthonycarbone** [comment]
All of backend had some cool little web apps to show off. We are now familiar with Postgres, Psycopg2 (to a degree), Flask/FastAPI.
