### ISSUE TITLE
FastAPI vs Flask

### ISSUE THREAD

**Issue by dennuguyen** [CreateUNSW/OWRxCREATE-Database-Venture#5]
From what I gather, there are two obvious choices for our API framework; FastAPI & Flask. Here are the pros and cons I've found in my research, add any that you come across...

**FastAPI**
- Good performance (not critical though)
- Supposedly faster to develop
- Automatically generated API documentation (yet to witness it though)

**Flask**
- More mature, more 'StackOverflow documentation'
- (Supposedly) simple
- More of the team are familiar with it from COMP courses

Let me know of any other ideas as to what to choose. @ShoreoNoSure why are you a proponent of FastAPI?

**Comment by anthonycarbone** [comment]
We decided on FastAPI!
